### ISSUE TITLE
Mejoras gráficas para la view sell asset 

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#656]

**Comment by emmysm** [comment]
Propuestas A
Full-screen
![propuestas-a-01](https://cloud.githubusercontent.com/assets/15143489/13866446/8478be52-ec87-11e5-8344-932eb7334359.png)

Propuestas B 

![propuesta b-02](https://cloud.githubusercontent.com/assets/15143489/13866449/8ae59788-ec87-11e5-9bf0-48f00e13200e.png)

@Fermat-ORG/skynet-team @javafrank

**Comment by javafrank** [comment]
I like the proposal A because it is a full screen dialog, although I do not agree with the "frame" around the controls, I prefer a much more simple and flat design of single labels and controls, i attached a link with some examples of text fields and how are designed, i still do not understand the sliders to enter the amount and how the user will interact with this, the design of autocomplete text seems very good, just seems multiple selection insted simple, an idea of autocomplete text is on the link.

me gusta más la propuesta A, ya que es un dialogo full screen, aunque no estoy de acuerdo con el diseño tipo marco alrededor de los controles, yo prefiero un diseño mucho mas sencillo y plano de solo etiquetas y controles, anexo un link con algunos ejemplos de campos de texto y como estan diseñados, sigo sin entender mucho los sliders para ingresar monto y como el usuario va a interactuar con esto, el diseño del autocomplete text me parece muy bueno, solo que parece seleccion multiple en lugar de simple, una idea para el autocomplete text está en el link.

https://www.google.com/design/spec/components/text-fields.html

**Comment by jinmyjbv** [comment]
I like the third option from the last proposal, i think because of the small quantities of bitcoins that are usually used, it would be too complicated to set the bitcoin ammount through a slider for the end user like is shown in the other examples.

me gusta la tercera opción de la ultima propuesta, pienso que por las cantidades pequeñas de bitcoins que se usan constantemente seria muy complicado para el usuario final establecer la cantidad mediante un slider como se muestra en los otros modelos.

**Comment by pennyxz** [comment]
I like proposal B, Number 3. But I don't really like the frames around the components. I think a simple label its better with some separators, maybe. I like the autocomplete text desing too.

**Comment by emmysm** [comment]
Proposal 1
![sell-asset0](https://cloud.githubusercontent.com/assets/15143489/13896287/a7bd7bf6-ed58-11e5-881d-0bce28672ba3.png)

Proposal 2

![sell-asset](https://cloud.githubusercontent.com/assets/15143489/13896288/a7c34072-ed58-11e5-94f0-039af5925d51.png)

@Fermat-ORG/skynet-team @javafrank @yojoaquin

**Comment by arnaldos** [comment]
@emmysm Expands the area of ​​the pop-up  to fit more users, places a shadow below the pop-up

**Comment by emmysm** [comment]
![sell asset-03](https://cloud.githubusercontent.com/assets/15143489/13978001/b9bbcf16-f09f-11e5-8cdf-95526fc4639f.png)

@Fermat-ORG/skynet-team @javafrank @arnaldos

**Comment by javafrank** [comment]
fine, i like the proposal 2, but i think it is too expanded
