### ISSUE TITLE
Improve asset transfer user view wallet DAP

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#724]

**Comment by emmysm** [comment]
![sin titulo-3](https://cloud.githubusercontent.com/assets/15143489/13977299/fb5b63ec-f099-11e5-8b38-5bfe1762c767.png)

@Fermat-ORG/skynet-team @javafrank

**Comment by pennyxz** [comment]
I like proposal 2. Like Redeem Asset, maybe you can do something about the check of the selected user,    because we can't see the selection clearly. I would like the button for Transfer in the top-right corner too. Pretty much the same I commented on [https://github.com/Fermat-ORG/fermat-graphic-design/issues/579#issuecomment-200392075](url)

Me gusta la propesta 2. Como en la propuesta de Redeem Point, podrias hacer algo para el check del usuario seleccionado, por que no se ve claramente. Tambien me gustaria un boton en la esquina superior derecha. Prácticamente todo lo que comente en [https://github.com/Fermat-ORG/fermat-graphic-design/issues/579#issuecomment-200392075](url)

**Comment by emmysm** [comment]
@pennyxz vale, igual por aca, ya genero los ajustes. En este caso el botón diría "Send"?

**Comment by javafrank** [comment]
i like the proposal 1, but i think the line must be below, as a separator, and the check needless because when tap the user the app must go to the action

me gusta la propuesta 1, pero pienso que la linea debe ir mas abajo, como un separador, y el check no es necesario debido a que cuando se seleccione al usuario se debe ir a la accion directamente.

**Comment by pennyxz** [comment]
@emmysm I think its should be Transfer, @nindriago please, can you verify this?

**Comment by nindriago** [comment]
yes, I think is better, @emmysm let's try both and choose

**Comment by emmysm** [comment]
ok @pennyxz @nindriago

**Comment by emmysm** [comment]
![redeem-01](https://cloud.githubusercontent.com/assets/15143489/14002069/a5781876-f11b-11e5-9ab2-a68d382189a9.png)

@Fermat-ORG/skynet-team @javafrank

**Comment by pennyxz** [comment]
I really like proposal 1 and 2. I think I can't choose. 
@Fermat-ORG/skynet-team @javafrank Help me choosing

@emmysm Don't forget the checks!

**Comment by jinmyjbv** [comment]
I think proposal 2 is better, i don't like having too much "only-text" buttons, but of course this is just my opinion
